model:
  base_learning_rate: 0.000001
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 100
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: class_label
    image_size: 8 #After downscale (A)
    channels: 64 #After downscale (B)
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss
    use_ema: False    
    
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 8 #(A) Dependen on first stage
        in_channels: 64 #(B) Dependen on first stage
        out_channels: 64 #(B)
        model_channels: 192
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 5
        num_heads: 1
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 512
    
    first_stage_config:
      config_path: logs/2024-08-30T14-38-24_autoencoder_kl_8x8x64/autoencoder_kl_8x8x64.yaml
      ckpt_path: logs/2024-08-30T14-38-24_autoencoder_kl_8x8x64/checkpoints/last.ckpt
    
    cond_stage_config:
      target: ldm.modules.encoders.modules.ClassEmbedder
      params:
        n_classes: 3
        embed_dim: 512
        key: class_label

data:
  target: main.DataModuleFromConfig
  
  params:
    batch_size: 64
    wrap: True
    num_workers: 16 # Depends on the maschien
    train:
      target: ldm.data.nakoT2w.ImageSRTrain
      params:
        size: 256
        class_labels: true
    validation:
      target: ldm.data.nakoT2w.ImageSRValidation
      params:
        size: 256
        class_labels: true

trainer:
  max_epochs: 10000
