model:
  base_learning_rate: 0.000001
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 400
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: c_concat
    image_size: 8 #After downscale (A)
    channels: 64 #After downscale (B without concat; is used to creat the random noise for sampling)
    cond_stage_trainable: false # We do not want the encoder to be trained.
    conditioning_key: concat # hybrid,crossattn,concat
    monitor: val/loss
    use_ema: True    
    
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 8 #(A) Dependen on first stage
        in_channels: 128 #(B+concat) Dependen on first stage
        out_channels: 64 #(B)
        model_channels: 192
        attention_resolutions: []
        #- 8
        #- 4
        #- 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 5
        num_heads: 1
        use_spatial_transformer: false
        #transformer_depth: 1
        #context_dim: 512
    
    first_stage_config:
      config_path: logs/2024-09-10T10-28-33_autoencoder_kl_8x8x64_gray/autoencoder_kl_8x8x64_gray.yaml
      ckpt_path: logs/2024-09-10T10-28-33_autoencoder_kl_8x8x64_gray/checkpoints/last.ckpt
    
    cond_stage_config:
      config_path: logs/2024-09-10T10-28-33_autoencoder_kl_8x8x64_gray/autoencoder_kl_8x8x64_gray.yaml
      ckpt_path: logs/2024-09-10T10-28-33_autoencoder_kl_8x8x64_gray/checkpoints/last.ckpt
    #python main.py --base configs/latent-diffusion/T2w_2_ct.yaml -t --gpus 0,   
    #  target: ldm.modules.encoders.modules.ClassEmbedder
    #  params:
    #    n_classes: 3
    #    embed_dim: 512
    #    key: class_label

data:
  target: main.DataModuleFromConfig
  
  params:
    batch_size: 64
    wrap: True
    num_workers: 16 # Depends on the maschien
    train:
      target: ldm.data.T2w_2_CT.ImageSRTrain
      params:
        size: 256
    validation:
      target: ldm.data.T2w_2_CT.ImageSRValidation
      params:
        size: 256

trainer:
  max_epochs: 10000
